name: Package Wallet for Windows with Pyinstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: Wallet

    - uses: actions/upload-artifact@v2
      with:
        name: wallet-windows
        path: Wallet/dist/windows
