name: Package Wallet for Windows with Pyinstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: Wallet
        
    - uses: actions/upload-artifact@v2
      with:
        name: wallet-windows
        path: Wallet/dist/windows

        
  sign:
    needs: build
    runs-on: windows-latest
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: wallet-windows
        path: binaries

    - uses: Dana-Woo/code-sign-action@v4
      with:
        certificate: '${{ secrets.CERTIFICATE }}'
        password: '${{ secrets.PASSWORD }}'
        folder: 'binaries'
        
    - uses: actions/upload-artifact@v2
      with:
        name: wallet-windows
        path: binaries
