name: Package Wallet for Windows with Pyinstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: Wallet

        
  sign:
    runs-on: windows-latest
    steps:
    - uses: DanaBear/code-sign-action@v4
      with:
        certificate: '${{ secrets.CERTIFICATE }}'
        password: '${{ secrets.PASSWORD }}'
        certificatesha1: '${{ secrets.CERTHASH }}'
        certificatename: '${{ secrets.CERTNAME }}'
        folder: 'Wallet/dist/windows'
        
  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/upload-artifact@v2
        with:
          name: wallet-windows
          path: Wallet/dist/windows
