name: Package Wallet for Windows with Pyinstaller

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'Wallet'
  pull_request:
    branches: [ main ]
    paths:
      - 'Wallet'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application Windows
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: Wallet
        
    - name: Package Application Linux
      uses: JackMcKew/pyinstaller-action-linux@main
      with:
        path: Wallet
        
        
    - uses: actions/upload-artifact@v2
      with:
        name: wallet-windows
        path: Wallet/dist/windows
        
    - uses: actions/upload-artifact@v2
      with:
        name: wallet-linux
        path: Wallet/dist/linux

        
  sign:
    needs: build
    runs-on: windows-latest
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: wallet-windows
        path: unsigned
        

    - uses: MurrayGroves/code-sign-action@v6
      with:
        certificate: '${{ secrets.CERTIFICATE }}'
        password: '${{ secrets.PASSWORD }}'
        certificatename: '${{ secrets.CERTNAME }}'
        folder: 'unsigned'
        timestampUrl: 'http://timestamp.digicert.com'
        
    - uses: actions/upload-artifact@v2
      with:
        name: wallet-windows-signed
        path: unsigned
        
  release:
    needs: sign
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: wallet-windows
          path: unsigned
      
      - uses: actions/download-artifact@v2
        with:
          name: wallet-windows-signed
          path: signed

      - uses: actions/download-artifact@v2
        with:
          name: wallet-linux
          path: linux
          
      - name: copy file
        uses: canastro/copy-file-action@master
        with:
          source: "unsigned/wallet.exe"
          target: "unsigned/wallet-unsigned.exe"
    
      - name: "Build & test"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: latest
          title: Wallet
          files: |
            unsigned/wallet-unsigned.exe
            signed/wallet.exe
            linux/wallet
            
          
