name: Package Wallet for Windows with Pyinstaller

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'Wallet'
  pull_request:
    branches: [ main ]
    paths:
      - 'Wallet'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application Windows
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: Wallet
        
    - name: Package Application Linux
      uses: JackMcKew/pyinstaller-action-linux@main
      with:
        path: Wallet
        
        
    - uses: actions/upload-artifact@v2
      with:
        name: wallet-windows
        path: Wallet/dist/windows
        
    - uses: actions/upload-artifact@v2
      with:
        name: wallet-linux
        path: Wallet/dist/linux

        
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: wallet-windows
          path: windows
      

      - uses: actions/download-artifact@v2
        with:
          name: wallet-linux
          path: linux

      - name: copy file
        uses: canastro/copy-file-action@master
        with:
          source: "linux/wallet"
          target: "linux/wallet-linux"
          
      - name: "Build & test"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: latest
          title: Wallet
          files: |
            windows/wallet.exe
            linux/wallet-linux
            
          
